[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ecdsa>=0.19.1",
    "flask>=3.1.1",
    "flask-cors>=4.0.0",
    "pycryptodome>=3.23.0",
    "requests>=2.31.0",
]
